# Generated by Django 4.0.5 on 2022-07-01 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_description', models.CharField(blank=True, help_text='Введите описание Животного', max_length=200, null=True, verbose_name='Описание Животного')),
                ('animal_age_min', models.IntegerField(help_text='Введите минимальный Возраст', null=True, verbose_name='Минимальный Возраст')),
                ('animal_age_max', models.IntegerField(help_text='Введите максимальный Возраст', null=True, verbose_name='Максимальный Возраст')),
                ('weight_min', models.IntegerField(help_text='Выберите вес Животного (от)', null=True, verbose_name='Минимальный вес Животного')),
                ('weight_max', models.IntegerField(help_text='Выберите вес Животного (до)', null=True, verbose_name='Максимальный вес Животного')),
            ],
        ),
        migrations.CreateModel(
            name='BirdsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип птицы', max_length=200, verbose_name='Птица')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите страну изготовителя', max_length=200, verbose_name='Страна изготовитель')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Выберите вес продукта', null=True, verbose_name='Вес продукта')),
                ('maker', models.CharField(blank=True, help_text='Введите Производителя', max_length=200, null=True, verbose_name='Производитель')),
                ('country', models.ForeignKey(help_text='Выберите страну изготовителя', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна изготовитель')),
                ('industry', models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.industry', verbose_name='Отрасль')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип сырья', max_length=200, verbose_name='Тип Сырья')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите Отрасль', max_length=50, verbose_name='Отрасль')),
            ],
        ),
        migrations.CreateModel(
            name='BVMK',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'БВМК',
                'verbose_name_plural': 'БВМК',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Cows',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            options={
                'verbose_name': 'Корова',
                'verbose_name_plural': 'Коровы',
            },
            bases=('catalog.animal',),
        ),
        migrations.CreateModel(
            name='Kombikorm',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Комбикорм',
                'verbose_name_plural': 'Комбикорм',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
            ],
            options={
                'verbose_name': 'Свинья',
                'verbose_name_plural': 'Свиньи',
            },
            bases=('catalog.animal',),
        ),
        migrations.CreateModel(
            name='Premix',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Премикс',
                'verbose_name_plural': 'Премикс',
            },
            bases=('catalog.product',),
        ),
        migrations.AddField(
            model_name='industry',
            name='industry_animal',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typeofindustry', verbose_name='Отрасль'),
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, help_text='Введите название Товара', max_length=200, verbose_name='Название Товара')),
                ('image', models.IntegerField(default=0, help_text='Введите картинку продукта', verbose_name='Картинка')),
                ('date', models.DateField(blank=True, help_text='Введите дату добавления товара', null=True, verbose_name='Дата добавления товара')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Введите цену ', max_digits=10, verbose_name='Цена')),
                ('summary', models.TextField(blank=True, help_text='Введите описание товара', max_length=1000, null=True, verbose_name='Описание товара')),
                ('blending', models.TextField(blank=True, help_text='Введите описание по смешиванию', max_length=1000, null=True, verbose_name='Описание по смешиванию')),
                ('animal', models.ForeignKey(blank=True, help_text='Выберите Животное', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.animal', verbose_name='Животное')),
                ('product', models.ForeignKey(help_text='Выберете продукт', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='industry',
            field=models.ForeignKey(help_text='Выберите Отрасль', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.industry', verbose_name='Отрасль'),
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.product')),
                ('materials_type', models.ForeignKey(blank=True, help_text='Выберите тип Сырья', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.typematerial', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Birds',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.animal')),
                ('animal_type', models.ForeignKey(blank=True, help_text='Выберите тип Птицы', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.birdstype', verbose_name='Птица')),
            ],
            options={
                'verbose_name': 'Птица',
                'verbose_name_plural': 'Птицы',
            },
            bases=('catalog.animal',),
        ),
    ]
