# Generated by Django 4.0.5 on 2022-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default=0, help_text='Введите картинку продукта', upload_to='', verbose_name='Картинка'),
        ),
    ]
