# Generated by Django 4.0.5 on 2022-07-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_good_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_age_max',
            field=models.DecimalField(decimal_places=2, help_text='Введите максимальный Возраст', max_digits=5, null=True, verbose_name='Максимальный Возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_age_min',
            field=models.DecimalField(decimal_places=2, help_text='Введите минимальный Возраст', max_digits=5, null=True, verbose_name='Минимальный Возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight_max',
            field=models.DecimalField(decimal_places=2, help_text='Выберите вес Животного (до)', max_digits=5, null=True, verbose_name='Максимальный вес Животного'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='weight_min',
            field=models.DecimalField(decimal_places=2, help_text='Выберите вес Животного (от)', max_digits=5, null=True, verbose_name='Минимальный вес Животного'),
        ),
    ]
