# Generated by Django 4.0.5 on 2022-07-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_animal_animal_age_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birdstype',
            options={'verbose_name': 'Тип птицы', 'verbose_name_plural': 'Типы птицы'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name': 'Отрасль', 'verbose_name_plural': 'Отрасли'},
        ),
        migrations.AlterModelOptions(
            name='typematerial',
            options={'verbose_name': 'Тип сырья', 'verbose_name_plural': 'Типы сырья'},
        ),
        migrations.AlterModelOptions(
            name='typeofindustry',
            options={'verbose_name': 'Тип Отрасли', 'verbose_name_plural': 'Типы Отрасли'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_age_max',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='animal_age_min',
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_day_max',
            field=models.IntegerField(blank=True, help_text='Введите максимальный Возраст в днях', null=True, verbose_name='Максимальный Возраст в днях'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_day_min',
            field=models.IntegerField(blank=True, help_text='Введите минимальный Возраст в днях', null=True, verbose_name='Минимальный Возраст в днях'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_month_max',
            field=models.IntegerField(blank=True, help_text='Введите максимальный Возраст в месяцах', null=True, verbose_name='Максимальный Возраст в месяцах'),
        ),
        migrations.AddField(
            model_name='animal',
            name='animal_month_min',
            field=models.IntegerField(blank=True, help_text='Введите минимальный Возраст в месяцах', null=True, verbose_name='Минимальный Возраст в месяцах'),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default=0, help_text='Добавьте картинку продукта', upload_to='', verbose_name='Картинка'),
        ),
    ]
